# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--XPSmSLQM7BWaGSCX7Dxz5GmqVr_wC_
"""

# MoneyMate - Your Personal Finance Assistant
# Complete single-cell solution for Google Colab

# ============= INSTALLATION =============
import subprocess
import sys

def install_packages():
    packages = [
        'gradio',
        'transformers',
        'torch',
        'plotly',
        'pandas',
        'numpy',
        'accelerate'
    ]
    for package in packages:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("📦 Installing packages...")
install_packages()
print("✅ Packages installed!")

# ============= IMPORTS =============
import gradio as gr
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import json
import random

# ============= CONFIGURATION =============
# 🔑 ADD YOUR HUGGINGFACE TOKEN HERE
HF_TOKEN = "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"  # Get from: https://huggingface.co/settings/tokens
MODEL_NAME = "ibm-granite/granite-3.1-2b-instruct"

# Initialize the model pipeline
tokenizer = None
model_pipeline = None

def initialize_model():
    """Initialize the model with proper error handling"""
    global tokenizer, model_pipeline

    if HF_TOKEN == "YOUR_HUGGINGFACE_TOKEN_HERE":
        print("⚠️ Please add your HuggingFace token")
        return False

    try:
        from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
        import torch

        print("🔄 Loading model... This may take a minute on first run...")

        # Load tokenizer and model
        tokenizer = AutoTokenizer.from_pretrained(
            MODEL_NAME,
            token=HF_TOKEN,
            trust_remote_code=True
        )

        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            token=HF_TOKEN,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="auto" if torch.cuda.is_available() else None,
            trust_remote_code=True
        )

        model_pipeline = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=500,
            do_sample=True,
            temperature=0.7,
            top_p=0.9
        )

        print("✅ Model loaded successfully!")
        return True

    except Exception as e:
        print(f"❌ Error loading model: {e}")
        print("💡 The app will still work, but chatbot will be disabled.")
        return False

# Try to initialize
model_loaded = initialize_model()

# ============= FEATURE 2: FINANCE PERSONALITY SCANNER =============
PERSONALITY_QUIZ = [
    {
        "question": "When you receive unexpected money (bonus/gift), what do you do first?",
        "options": ["Save it immediately", "Spend it on something I want", "Invest it for growth", "Analyze all options for days"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "How do you feel about checking your bank balance?",
        "options": ["I check it daily", "I avoid looking at it", "I track it in spreadsheets", "I stress about it constantly"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 1], "overthinker": [1, 0, 0, 3]}
    },
    {
        "question": "Your approach to shopping is:",
        "options": ["Buy only what I need", "Treat myself often", "Calculate ROI on purchases", "Compare prices for hours"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 1, 3]}
    },
    {
        "question": "When investing, you prefer:",
        "options": ["Fixed deposits/Safe options", "I don't invest much", "Stocks and mutual funds", "Reading reviews endlessly"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 1, 3]}
    },
    {
        "question": "Your emergency fund status:",
        "options": ["6+ months saved", "What emergency fund?", "Invested for growth", "I keep planning to start"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "How do you handle bills?",
        "options": ["Pay early or on time", "Last minute rush", "Automated everything", "Worry about them constantly"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "Your retirement planning is:",
        "options": ["Already saving aggressively", "I'll think about it later", "Diversified portfolio ready", "Overwhelmed by options"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "When friends suggest an expensive outing:",
        "options": ["Suggest cheaper alternatives", "I'm in! YOLO", "Calculate if it fits my budget", "Stress about saying yes/no"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "Your knowledge about taxes:",
        "options": ["I maximize all deductions", "Minimal effort", "I study tax-saving investments", "I research but feel confused"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 1], "overthinker": [0, 0, 0, 3]}
    },
    {
        "question": "How do you track expenses?",
        "options": ["Detailed budgeting app", "I don't track", "Investment dashboard", "Multiple apps, still confused"],
        "weights": {"saver": [3, 0, 1, 0], "spender": [0, 3, 0, 0], "investor": [1, 0, 3, 0], "overthinker": [0, 0, 0, 3]}
    }
]

PERSONALITY_PROFILES = {
    "saver": {
        "title": "🏦 The Saver",
        "description": "You're disciplined and security-focused. You prioritize saving and rarely splurge.",
        "strengths": "• Strong emergency fund\n• Low debt\n• Financial security\n• Good at delayed gratification",
        "improvements": "• Consider growth investments\n• Allow yourself small rewards\n• Balance security with growth\n• Don't miss life experiences",
        "advice": "You're great at saving! Now focus on making your money work harder through smart investments. A balanced portfolio can grow your wealth while maintaining security."
    },
    "spender": {
        "title": "🛍️ The Spender",
        "description": "You live in the moment and enjoy spending on experiences and things you love.",
        "strengths": "• Enjoy life fully\n• Not stressed about money\n• Value experiences\n• Spontaneous and fun",
        "improvements": "• Start a 20% savings rule\n• Build emergency fund\n• Track expenses\n• Automate savings before spending",
        "advice": "Your zest for life is admirable! Start small: save 20% of income first, then enjoy the rest guilt-free. Automate savings so you don't have to think about it."
    },
    "investor": {
        "title": "📈 The Investor",
        "description": "You're growth-focused and understand money multiplication through smart investments.",
        "strengths": "• Wealth building mindset\n• Understands compound growth\n• Diversified portfolio\n• Long-term thinking",
        "improvements": "• Maintain emergency liquidity\n• Balance risk appetite\n• Don't forget life goals\n• Review portfolio quarterly",
        "advice": "Excellent strategy! Ensure you have 6 months of expenses in liquid funds before aggressive investing. Keep learning and stay diversified!"
    },
    "overthinker": {
        "title": "🤔 The Overthinker",
        "description": "You analyze everything but struggle to take action due to information overload.",
        "strengths": "• Thorough research\n• Risk-aware\n• Detail-oriented\n• Careful decision maker",
        "improvements": "• Set decision deadlines\n• Start with small steps\n• Accept imperfect action\n• Use simple rules: 50-30-20 budget",
        "advice": "Analysis is good, but paralysis hurts growth. Use the 50-30-20 rule: 50% needs, 30% wants, 20% savings. Start with index funds – less to overthink!"
    }
}

quiz_state = {"current": 0, "scores": {"saver": 0, "spender": 0, "investor": 0, "overthinker": 0}}

def start_quiz():
    """Initialize quiz"""
    quiz_state["current"] = 0
    quiz_state["scores"] = {"saver": 0, "spender": 0, "investor": 0, "overthinker": 0}

    q = PERSONALITY_QUIZ[0]
    return (
        f"**Question 1/10**\n\n{q['question']}",
        gr.Radio(choices=q['options'], value=None, visible=True),
        gr.Button(visible=True, value="Submit Answer"),
        gr.Markdown(visible=False),
        gr.Button(visible=False)
    )

def submit_answer(answer):
    """Process quiz answer"""
    if answer is None:
        return "Please select an answer!", gr.Radio(), gr.Button(visible=True), gr.Markdown(visible=False), gr.Button(visible=False)

    current_q = PERSONALITY_QUIZ[quiz_state["current"]]
    answer_idx = current_q["options"].index(answer)

    for personality, weights in current_q["weights"].items():
        quiz_state["scores"][personality] += weights[answer_idx]

    quiz_state["current"] += 1

    if quiz_state["current"] < len(PERSONALITY_QUIZ):
        q = PERSONALITY_QUIZ[quiz_state["current"]]
        return (
            f"**Question {quiz_state['current'] + 1}/10**\n\n{q['question']}",
            gr.Radio(choices=q['options'], value=None),
            gr.Button(visible=True),
            gr.Markdown(visible=False),
            gr.Button(visible=False)
        )
    else:
        # Quiz complete - show results
        dominant = max(quiz_state["scores"], key=quiz_state["scores"].get)
        profile = PERSONALITY_PROFILES[dominant]

        result = f"""
# {profile['title']}

## 📊 Your Score Distribution
- 🏦 Saver: {quiz_state['scores']['saver']} points
- 🛍️ Spender: {quiz_state['scores']['spender']} points
- 📈 Investor: {quiz_state['scores']['investor']} points
- 🤔 Overthinker: {quiz_state['scores']['overthinker']} points

---

## Who You Are
{profile['description']}

## ✅ Your Strengths
{profile['strengths']}

## 🎯 Areas to Improve
{profile['improvements']}

## 💡 Personalized Advice
{profile['advice']}
"""

        return (
            result,
            gr.Radio(visible=False),
            gr.Button(visible=False),
            gr.Markdown(visible=True, value=result),
            gr.Button(visible=True, value="Take Quiz Again")
        )

# ============= FEATURE 3: GOAL VISUALIZER =============
def calculate_goal(goal_name, target_amount, current_savings, target_date, monthly_contribution):
    """Calculate and visualize savings goal"""
    try:
        target_amount = float(target_amount)
        current_savings = float(current_savings)
        monthly_contribution = float(monthly_contribution)

        if target_amount <= 0 or monthly_contribution < 0:
            return "❌ Please enter valid positive amounts", None

        # Calculate months until target
        target_datetime = datetime.strptime(target_date, "%Y-%m-%d")
        months_remaining = max(1, (target_datetime.year - datetime.now().year) * 12 +
                              (target_datetime.month - datetime.now().month))

        # Calculate required monthly savings
        amount_needed = target_amount - current_savings
        required_monthly = amount_needed / months_remaining if months_remaining > 0 else amount_needed

        # Progress calculation
        total_will_save = current_savings + (monthly_contribution * months_remaining)
        progress_percent = (total_will_save / target_amount) * 100

        # Create projection data
        months = []
        projected_savings = []
        current = current_savings

        for i in range(months_remaining + 1):
            months.append(datetime.now() + timedelta(days=30*i))
            projected_savings.append(current)
            current += monthly_contribution

        # Create visualization
        fig = go.Figure()

        # Add projected savings line
        fig.add_trace(go.Scatter(
            x=months,
            y=projected_savings,
            mode='lines+markers',
            name='Projected Savings',
            line=dict(color='#10b981', width=3),
            marker=dict(size=8)
        ))

        # Add target line
        fig.add_trace(go.Scatter(
            x=[months[0], months[-1]],
            y=[target_amount, target_amount],
            mode='lines',
            name='Target Amount',
            line=dict(color='#f59e0b', width=2, dash='dash')
        ))

        # Styling
        fig.update_layout(
            title=f"📊 {goal_name} - Savings Projection",
            xaxis_title="Date",
            yaxis_title="Amount (₹)",
            hovermode='x unified',
            template='plotly_dark',
            height=400,
            showlegend=True
        )

        # Create status message
        status_emoji = "✅" if progress_percent >= 100 else "⏳" if progress_percent >= 50 else "⚠️"

        status_message = f"""
## {status_emoji} Goal: {goal_name}

### 💰 Financial Summary
- **Target Amount:** ₹{target_amount:,.2f}
- **Current Savings:** ₹{current_savings:,.2f}
- **Amount Needed:** ₹{amount_needed:,.2f}

### 📅 Timeline
- **Target Date:** {target_date}
- **Months Remaining:** {months_remaining}

### 💵 Monthly Savings Plan
- **Your Contribution:** ₹{monthly_contribution:,.2f}/month
- **Required Amount:** ₹{required_monthly:,.2f}/month
- **Total by Target Date:** ₹{total_will_save:,.2f}

### 📈 Progress
- **Achievement Rate:** {progress_percent:.1f}%

---

"""

        if progress_percent >= 100:
            status_message += "🎉 **Excellent!** You'll exceed your goal with current contributions!"
        elif progress_percent >= 75:
            status_message += "✅ **On Track!** You're making great progress toward your goal!"
        elif progress_percent >= 50:
            status_message += "⚠️ **Needs Boost!** Consider increasing monthly contribution to ₹{:.2f}".format(required_monthly)
        else:
            status_message += "❌ **Action Required!** Increase monthly savings to ₹{:.2f} to reach your goal!".format(required_monthly)

        return status_message, fig

    except ValueError:
        return "❌ Please enter valid numbers for amounts", None
    except Exception as e:
        return f"❌ Error: {str(e)}", None

# ============= FEATURE 4: INVESTMENT ALARM SYSTEM =============
def generate_market_data():
    """Generate simulated market data for demonstration"""
    dates = pd.date_range(end=datetime.now(), periods=90, freq='D')

    # Simulate NIFTY 50
    nifty_base = 22000
    nifty_data = nifty_base + np.cumsum(np.random.randn(90) * 100)

    # Simulate Bank Nifty
    bank_nifty_base = 47000
    bank_nifty_data = bank_nifty_base + np.cumsum(np.random.randn(90) * 200)

    df = pd.DataFrame({
        'Date': dates,
        'NIFTY_50': nifty_data,
        'Bank_Nifty': bank_nifty_data
    })

    return df

def check_investment_opportunities():
    """Analyze market and provide investment insights"""
    df = generate_market_data()

    # Calculate metrics
    nifty_current = df['NIFTY_50'].iloc[-1]
    nifty_7d_ago = df['NIFTY_50'].iloc[-7]
    nifty_30d_ago = df['NIFTY_50'].iloc[-30]

    nifty_7d_change = ((nifty_current - nifty_7d_ago) / nifty_7d_ago) * 100
    nifty_30d_change = ((nifty_current - nifty_30d_ago) / nifty_30d_ago) * 100

    bank_nifty_current = df['Bank_Nifty'].iloc[-1]
    bank_nifty_7d_ago = df['Bank_Nifty'].iloc[-7]
    bank_nifty_30d_ago = df['Bank_Nifty'].iloc[-30]

    bank_nifty_7d_change = ((bank_nifty_current - bank_nifty_7d_ago) / bank_nifty_7d_ago) * 100
    bank_nifty_30d_change = ((bank_nifty_current - bank_nifty_30d_ago) / bank_nifty_30d_ago) * 100

    # Create visualization
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df['Date'],
        y=df['NIFTY_50'],
        mode='lines',
        name='NIFTY 50',
        line=dict(color='#3b82f6', width=2)
    ))

    fig.add_trace(go.Scatter(
        x=df['Date'],
        y=df['Bank_Nifty'],
        mode='lines',
        name='Bank Nifty',
        line=dict(color='#8b5cf6', width=2),
        yaxis='y2'
    ))

    fig.update_layout(
        title='📈 Market Trend Analysis (Last 90 Days)',
        xaxis_title='Date',
        yaxis_title='NIFTY 50',
        yaxis2=dict(
            title='Bank Nifty',
            overlaying='y',
            side='right'
        ),
        hovermode='x unified',
        template='plotly_dark',
        height=450
    )

    # Generate alerts
    alerts = []

    if nifty_7d_change < -3:
        alerts.append("🔔 **NIFTY 50 Alert**: Down {:.2f}% this week - Good SIP opportunity!".format(abs(nifty_7d_change)))

    if bank_nifty_7d_change < -4:
        alerts.append("🔔 **Bank Nifty Alert**: Down {:.2f}% this week - Banking sector correction!".format(abs(bank_nifty_7d_change)))

    if nifty_30d_change < -5:
        alerts.append("🎯 **Monthly Dip**: NIFTY down {:.2f}% this month - Strong buying opportunity for long-term!".format(abs(nifty_30d_change)))

    if not alerts:
        alerts.append("✅ Markets stable - Continue regular SIPs as planned")

    # Create report
    report = f"""
## 📊 Market Overview - {datetime.now().strftime('%B %d, %Y')}

### NIFTY 50
- **Current:** {nifty_current:,.2f}
- **7-Day Change:** {nifty_7d_change:+.2f}%
- **30-Day Change:** {nifty_30d_change:+.2f}%

### Bank Nifty
- **Current:** {bank_nifty_current:,.2f}
- **7-Day Change:** {bank_nifty_7d_change:+.2f}%
- **30-Day Change:** {bank_nifty_30d_change:+.2f}%

---

## 🔔 Investment Alerts

"""

    for alert in alerts:
        report += f"{alert}\n\n"

    report += """
---

## 💡 SIP Investment Tips

1. **Market Dips are Opportunities**: When indices fall 5-10%, it's historically a good time to increase SIPs
2. **Stay Consistent**: Continue regular SIPs regardless of market volatility
3. **Long-term View**: SIPs work best over 5+ years
4. **Diversify**: Don't put all money in one index

⚠️ **Disclaimer**: This is trend data, not financial advice. Consult a certified financial advisor before investing.
"""

    return report, fig

# ============= GRADIO INTERFACE =============
# Custom CSS for attractive UI
custom_css = """
.gradio-container {
    font-family: 'Inter', sans-serif !important;
}
.main-header {
    text-align: center;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 30px;
    border-radius: 10px;
    margin-bottom: 20px;
    color: white;
}
"""

# Build interface
with gr.Blocks(theme=gr.themes.Soft(), css=custom_css, title="MoneyMate") as app:

    gr.HTML("""
        <div class="main-header">
            <h1>💰 MoneyMate</h1>
            <p style="font-size: 18px; margin-top: 10px;">Your Intelligent Personal Finance Assistant</p>
        </div>
    """)

    with gr.Tabs():

        # TAB 1: Finance Chatbot
        with gr.Tab("🤖 Finance Chatbot"):
            gr.Markdown("""
            ### Ask me anything about:
            - 💼 Tax saving strategies
            - 📈 Investment planning
            - 💰 Budgeting tips
            - 🎯 Financial goals
            """)

            chatbot = gr.Chatbot(height=500, bubble_full_width=False)
            msg = gr.Textbox(
                placeholder="Ask me about taxes, investments, or saving tips...",
                label="Your Question"
            )
            clear = gr.Button("🗑️ Clear Chat")

            def respond(message, chat_history):
                if not model_loaded or HF_TOKEN == "YOUR_HUGGINGFACE_TOKEN_HERE":
                    bot_message = "⚠️ Please add your HuggingFace token in the code to use the chatbot feature."
                    chat_history.append((message, bot_message))
                    return "", chat_history

                try:
                    # Build conversation context
                    system_prompt = "You are MoneyMate, an expert personal finance advisor. Provide clear, helpful advice on taxes, investments, budgeting, and financial planning. Be concise and friendly.\n\n"

                    conversation = system_prompt

                    # Add chat history
                    for human, assistant in chat_history:
                        conversation += f"User: {human}\nAssistant: {assistant}\n\n"

                    # Add current message
                    conversation += f"User: {message}\nAssistant:"

                    # Generate response
                    result = model_pipeline(
                        conversation,
                        max_new_tokens=300,
                        do_sample=True,
                        temperature=0.7,
                        return_full_text=False
                    )

                    bot_message = result[0]['generated_text'].strip()

                    # Clean up response - remove any continuation of conversation
                    if "\nUser:" in bot_message:
                        bot_message = bot_message.split("\nUser:")[0].strip()

                    chat_history.append((message, bot_message))
                    return "", chat_history

                except Exception as e:
                    bot_message = f"⚠️ Error: {str(e)}\n\nTip: The model might still be loading. Try again in a moment, or use the other features!"
                    chat_history.append((message, bot_message))
                    return "", chat_history

            msg.submit(respond, [msg, chatbot], [msg, chatbot])
            clear.click(lambda: [], None, [chatbot], queue=False)

        # TAB 2: Personality Scanner
        with gr.Tab("🧠 Finance Personality Scanner"):
            gr.Markdown("""
            ### Discover Your Finance Personality!
            Take this 10-question quiz to understand your financial behavior and get personalized advice.
            """)

            quiz_question = gr.Markdown()
            quiz_options = gr.Radio(label="Choose your answer:", visible=False)
            submit_btn = gr.Button("Submit Answer", visible=False)
            quiz_result = gr.Markdown(visible=False)
            restart_btn = gr.Button("Take Quiz Again", visible=False)
            start_btn = gr.Button("🚀 Start Quiz", variant="primary", size="lg")

            start_btn.click(
                start_quiz,
                outputs=[quiz_question, quiz_options, submit_btn, quiz_result, restart_btn]
            )

            submit_btn.click(
                submit_answer,
                inputs=[quiz_options],
                outputs=[quiz_question, quiz_options, submit_btn, quiz_result, restart_btn]
            )

            restart_btn.click(
                start_quiz,
                outputs=[quiz_question, quiz_options, submit_btn, quiz_result, restart_btn]
            )

        # TAB 3: Goal Visualizer
        with gr.Tab("🎯 Goal Visualizer"):
            gr.Markdown("""
            ### Set and Track Your Financial Goals
            Enter your goal details to see how much you need to save monthly and track your progress!
            """)

            with gr.Row():
                with gr.Column():
                    goal_name_input = gr.Textbox(
                        label="Goal Name",
                        placeholder="e.g., New Bike, Europe Trip, Emergency Fund"
                    )
                    target_amount_input = gr.Number(
                        label="Target Amount (₹)",
                        value=100000
                    )
                    current_savings_input = gr.Number(
                        label="Current Savings (₹)",
                        value=20000
                    )
                    target_date_input = gr.Textbox(
                        label="Target Date (YYYY-MM-DD)",
                        value="2026-12-31"
                    )
                    monthly_contribution_input = gr.Number(
                        label="Monthly Contribution (₹)",
                        value=5000
                    )
                    calculate_btn = gr.Button("📊 Calculate My Plan", variant="primary")

                with gr.Column():
                    goal_status = gr.Markdown()
                    goal_chart = gr.Plot()

            calculate_btn.click(
                calculate_goal,
                inputs=[goal_name_input, target_amount_input, current_savings_input,
                       target_date_input, monthly_contribution_input],
                outputs=[goal_status, goal_chart]
            )

        # TAB 4: Investment Alarm
        with gr.Tab("📢 Investment Alarm System"):
            gr.Markdown("""
            ### Market Trend Analysis & SIP Opportunities
            Get alerts when markets dip and it's a good time to start or increase your SIPs!

            ⚠️ **Note**: This shows trend data for educational purposes, not financial advice.
            """)

            check_market_btn = gr.Button("🔍 Check Market Status", variant="primary", size="lg")
            market_report = gr.Markdown()
            market_chart = gr.Plot()

            check_market_btn.click(
                check_investment_opportunities,
                outputs=[market_report, market_chart]
            )

    gr.Markdown("""
    ---
    <div style="text-align: center; padding: 20px; opacity: 0.7;">
        <p>💡 MoneyMate - Powered by IBM Granite 3.3 2B Instruct</p>
        <p style="font-size: 12px;">⚠️ Disclaimer: This tool provides educational information and trend analysis.
        Always consult certified financial advisors before making investment decisions.</p>
    </div>
    """)

# ============= LAUNCH =============
if __name__ == "__main__":
    print("🚀 Launching MoneyMate...")
    print("⚠️  Remember to add your HuggingFace token in the code!")
    app.launch(share=True, debug=True)